---
plugin: aws_ec2
keyed_groups:
  - key: tags
    prefix: tag
hostnames:
  # a list in order of precedence for hostname variables.
  #
  - ip-address
  - dns-name
  - tag:Name
  - private-ip-address
filters:
  # All instances with their state as `running`
  instance-state-name: running
